name: "tests"
on:
  push:
    branches:
      - main
jobs:
  pipeline:
    name: "pipeline"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        uses: bahmutov/npm-install@master

      - name: Run Unit Tests
        run: npm run ci:test-unit

      - name: Run E2E Tests
        run: npm run ci:test-e2e

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
